# Generated by Django 4.0.3 on 2022-03-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speakers',
            new_name='Speaker',
        ),
    ]
